BasePath: /var/opt/fuzz/pggenfuzz
ArtefactsPath: path to arts
SquirrelTimeout: 172800
CheckTimeout: 600
Email:
  senderlogin: email bot login
  senderpassword: email bot pass
  receivers: user1@domain.com,user2@domain.com...
  hosting: smtp.yandex.ru
PGSettings:
  IsGit: true
  Branches:
    branch-name: descr
    another-branch: descr
  PGsource: path to pgsource
